### ISSUE TITLE
Lazer mods aren't being passed through to diffcalc

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-tools#123]
Commands such as `dotnet run -- simulate osu 165967 -m BL` don't work correctly at the moment, since mods are trimmed by `LegacyHelper`.

I'm getting around this locally at the moment by [removing the relevant method](https://github.com/apollo-dw/osu-tools/tree/remove-legacy-trim). Smoogi seemed certain that this would break calculation however I can confirm that osu-tools functions just fine without the method? I can PR the linked branch however I really doubt that this is the correct way to solve this.

**Comment by smoogipoo** [comment]
This one’s actually the important one: https://github.com/ppy/osu-tools/pull/113 It has test profile test cases in there to compare against. I’m fairly certain it still is required.

Perhaps it’s only the profile command that needs the trimming (it can also likely be done in a better way…).

**Comment by minisbett** [comment]
Resolved via #216
