### ISSUE TITLE
Invalid json returned for beatmaps with double quotes in beatmap name

### ISSUE THREAD

**Issue by MrHeliX** [ppy/osu-tools#141]
Example: `dotnet PerformanceCalculator.dll simulate catch ./cache/1113356.osu -j` will return a json object which includes a beatmap field with value: `"Various Artists - The Seven Deadly Sins Series Maps Compilation (CLSW) [Chapter II. Leviathan, The "Invidia" (Pet Peeve)]"`

The difficulty name contains unescaped double quotes. Because of this, the entire json is invalid

**Comment by joseph-ireland** [comment]
"Various Artists - The Seven Deadly Sins Series Maps Compilation (CLSW) [Chapter II. Leviathan, The “Invidia” (Pet Peeve)]" doesn't contain unescaped quotes - they're unicode left/right quote characters.

**Comment by peppy** [comment]
@MrHeliX how are you confirming the json is invalid in this case?

**Comment by MrHeliX** [comment]
Alright seems like when you use the `-o` parameter to save the response in a file, it actually does use the left/right quote characters which seems to be valid. But without that parameter I am getting regular double quotes.

@peppy My application reads the response from the command (without `-o`) and tries to parse it to JSON. It crashed only on those maps with the quotes. As a test I copied the response I got from osu-tools and pasted it in an online JSON parser which also marked it as invalid because of those quotes ([this](http://json.parser.online.fr/) for example)
![firefox_2022-01-09_15-04-09](https://user-images.githubusercontent.com/17840315/148685588-ce47f7ad-97c3-49dd-8cbf-785dac52cca6.png)

**Comment by joseph-ireland** [comment]
Seems to be a weird windows shell feature - the following program outputs regular double quotes when run in powersell/cmd, but keeps the unicode characters in git bash.
```
using System;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("“Hello world!”");
        }
    }
}

```

**Comment by peppy** [comment]
Are you reproducing this by copying from a shell window? That shouldn't be how you consume the json programmatically if so. Pipe or redirect it to the consumer. The shell should not have a say in adjusting the output content.

**Comment by joseph-ireland** [comment]
Just to be clear: the command 

`dotnet PerformanceCalculator.dll simulate catch 1113356 -j >output_file`

```
Console.WriteLine("“Hello world!”");
```

**Comment by joseph-ireland** [comment]
Just to be clear: the command

```
dotnet PerformanceCalculator.dll simulate catch 1113356 -j >output_file
```

stores invalid json in the file by default on windows. 

Manually setting utf8 output changes that - the following works:

```
Console.OutputEncoding = System.Text.Encoding.UTF8;
Console.WriteLine("“Hello world!”");
```

**Comment by peppy** [comment]
interesting, we probably want to make that change then, to better support windows users.
