### ISSUE TITLE
.NET core incompatibilies

### ISSUE THREAD

**Issue by kornkaobat** [ppy/osu-tools#46]
osu-tools only supports 
`<TargetFramework>netcoreapp2.0</TargetFramework>` 
but osu repo which is used by this repo needs `<TargetFramework>netstandard2.1</TargetFramework>` 
which is included only in .NET Core 3.0+ 
Resulting in this error when trying to run 
`dotnet run -- simulate osu "C:\Users\Korn\AppData\Local\osu!\Songs\1116349 Ariabl'eyeS - Kegare Naki Bara Juuji\Ariabl'eyeS - Kegare Naki Bara Juuji (Reform) [Anguish].osu " -a 98.96 -m hr -m hd -o whitecatkegare.txt`
`C:\Users\Korn\osu-tools\PerformanceCalculator\PerformanceCalculator.csproj : error NU1201: Project osu.Game.Rulesets.Catch is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Project osu.Game.Rulesets.Catch supports: netstandard2.1 (.NETStandard,Version=v2.1)`

**Comment by smoogipoo** [comment]
Ah, I'd forgotten the PR was broken. Will be fixed via https://github.com/ppy/osu-tools/pull/45 .
